generate_config:
  name: Generate Configuration
  description: Generate a Home Assistant configuration using AI
  fields:
    prompt:
      name: Prompt
      description: Natural language description of what you want to create
      required: true
      example: "Turn on living room lights when motion is detected after sunset"
      selector:
        text:
          multiline: true
    type:
      name: Configuration Type
      description: Type of configuration to generate
      required: false
      default: automation
      example: "automation"
      selector:
        select:
          options:
            - automation
            - script
            - scene
            - dashboard
            - template

reload:
  name: Reload Integration
  description: Reload the AI Configuration Assistant integration without restarting Home Assistant
  fields: {}
    context:
      name: Context
      description: Additional context or requirements
      required: false
      example: "Use only Zigbee devices"
      selector:
        object:

validate_config:
  name: Validate Configuration
  description: Validate a YAML configuration
  fields:
    config:
      name: Configuration
      description: YAML configuration to validate
      required: true
      example: |
        alias: Example Automation
        trigger:
          - platform: state
            entity_id: binary_sensor.motion
            to: 'on'
      selector:
        text:
          multiline: true
    type:
      name: Configuration Type
      description: Type of configuration to validate
      required: false
      default: automation
      selector:
        select:
          options:
            - automation
            - script
            - scene
            - dashboard
            - template

reload:
  name: Reload Integration
  description: Reload the AI Configuration Assistant integration without restarting Home Assistant
  fields: {}

preview_config:
  name: Preview Configuration
  description: Preview a configuration with live entity data
  fields:
    config:
      name: Configuration
      description: YAML configuration to preview
      required: true
      selector:
        text:
          multiline: true
    type:
      name: Configuration Type
      description: Type of configuration to preview
      required: false
      default: automation
      selector:
        select:
          options:
            - automation
            - script
            - scene
            - dashboard
            - template

reload:
  name: Reload Integration
  description: Reload the AI Configuration Assistant integration without restarting Home Assistant
  fields: {}